version: 0.2

phases:
  install:
    runtime-versions:
      kubectl: 1.32
    commands:
      - echo "Installing AWS CLI and updating kubeconfig"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - ./aws/install
      # Configure access to EKS cluster
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

  pre_build:
    commands:
      - echo "Verifying kubectl connectivity"
      - kubectl get nodes

  build:
    commands:
      - echo "Deploying Kubernetes manifests from repository root"
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

  post_build:
    commands:
      - echo "Verifying deployment status"
      - kubectl get pods
      - kubectl get svc

artifacts:
  files:
    - deployment.yaml
    - service.yaml
